# Target specific macros
TARGET = controller_b
TARGET_SOURCES = \
	controller_b.c
TOPPERS_OSEK_OIL_SOURCE = ./controller_b.oil

# Don't modify below part
O_PATH ?= build
include ../../ecrobot/ecrobot.mak
